### PR TITLE
formatter: Fix crash caused by an alignment of null statement

### LINKED ISSUE #824: Crash if class has double semicolon item
**Test case**

```systemverilog
class sample;
bit a;;
bit b;
endclass
```

Works for module, program but not class

**Error message output**
F20210519 17:24:37.693542 23043 logging.h:39] Check failed: t != nullptr unwrapped_line.Origin()
*** Check failure stack trace: ***
    @           0x4b59ef  google::LogMessage::SendToLog()
    @           0x4b4879  google::LogMessage::Flush()
    @           0x4b6249  google::LogMessageFatal::~LogMessageFatal()
    @           0x450950  verible::AlignablePartitionGroup::CalculateAlignmentSpacings()
    @           0x452a2e  verible::AlignablePartitionGroup::Align()
    @           0x436f73  verilog::formatter::TabularAlignTokenPartitions()
    @           0x423f15  verible::VectorTree<>::ApplyPreOrder()
    @           0x423f31  verible::VectorTree<>::ApplyPreOrder()
    @           0x429441  verilog::formatter::Formatter::Format()
    @           0x42af32  verilog::formatter::FormatVerilog()
    @           0x414829  main
    @     0x7fcf3ab12555  __libc_start_main
    @           0x419a9e  (unknown)
    @              (nil)  (unknown)

### PR DESCRIPTION
**Pull request by ldalek-antmicro**
Fixes #824

### CODE REVIEW

File: verilog/formatting/tree_unwrapper.cc [hunk 1]
```diff
@@ -1923,6 +1923,15 @@ void TreeUnwrapper::Visit(const verible::SyntaxTreeLeaf& leaf) {
   // Should be equivalent to AdvanceNextUnfilteredToken().
   AddTokenToCurrentUnwrappedLine();
 
+  // Make sure that newly extended unwrapped line has origin symbol
+  // FIXME: Pretty sure that this should be handled in an other way,
```
Comment (hzeller) [inline verilog/formatting/tree_unwrapper.cc:1927]: CC @fangism who might have a good guidance of how _should be handled in an other way_ can be

**Review by hzeller — APPROVED** [review]
LGTM
Ready to merge once CI is through.

File: verilog/formatting/tree_unwrapper.cc (hunk 1 above)
Comment (fangism) [reply verilog/formatting/tree_unwrapper.cc:1927]: Generally, the origin pointer is a little trickier when partitions reshape and boundaries move.  Its intent was to help with context-sensitive formatting decisions like alignment and diagnostics.  

This case is interesting because a `;` by itself is a [kNullDeclaration](https://cs.opensource.google/verible/verible/+/master:verilog/parser/verilog.y;drc=61a6c055aad09454994f353e091dfb9b9cfb9a21;l=1312) symbol.
Maybe the partition construction should treat this symbol as a valid class-item for the purpose of alignment, but perhaps ignore it because it doesn't match the structure of other declarations.  Alignment-wise, it can be treated as an ignored row.
